Add settings option to forcibly change language to English
maks/MGit pull request #557
Opened 2020-11-01 19:16 UTC by prattpratt

2020-11-04 23:53 UTC, maks commented
Thank you for contributing this, I'll try to have a look through it soon.

2020-11-13 08:40 UTC, prattpratt commented
@maks this is really tiny PR. So it does not take much time to review.

2020-11-22 22:56 UTC, maks requested changes
Thank you for contributing this and apologies for the delay in reviewing. Looks good, just a few comments regarding naming.

2020-11-22 22:56 UTC, maks commented on app/src/main/res/values/strings.xml
> +    <string name="preference_eng_lang">English Language</string>
please name this to more clearly indicate its purpose, eg "Use English to override device language"

2020-11-22 22:56 UTC, maks commented on app/src/main/java/me/sheimi/android/activities/SheimiFragmentActivity.java
> +    private void updateLocale(boolean isEngLang) {
pls see other comment regarding parameter naming

2020-12-01 17:59 UTC, prattpratt commented on app/src/main/res/values/strings.xml
> +    <string name="preference_eng_lang">English Language</string>
This is title, it should be short, but Ive added more clear summary.

2020-12-01 17:59 UTC, prattpratt commented on app/src/main/java/me/sheimi/android/utils/Profile.java
> +    public static boolean isEngLang(Context context) {
Done

2020-12-01 18:00 UTC, prattpratt commented on app/src/main/java/me/sheimi/android/activities/SheimiFragmentActivity.java
> +    private void updateLocale(boolean isEngLang) {
Done

2020-12-21 06:44 UTC, maks commented
Thank you for contributing this and apologies for taking so long to this in.

2020-12-21 21:43 UTC, merged